name: Release Build

on:
  push:
    branches:
      - main
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --stacktrace

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-mod
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: built-mod
          path: build/libs

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          tag_name: ${{ github.ref }}
          body: "Automated release build for ${{ github.ref }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

